version: '3.8'

services:

    pg1:
        image: postgres
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=db
        volumes:
            - $PWD/volume/pg:/var/lib/postgresql/data
        networks:
            - angular-dotnet-network

    dev1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dev
        ports:
            - "8080:8080"
            - "3000:3000"
        stdin_open: true
        tty: true
        environment:
            - NG_CLI_ANALYTICS=false
            - DATABASE_URL=postgres://user:password@pg1/db
        depends_on:
            - pg1
        volumes:
            - $PWD/volume/app:/app
        networks:
            - angular-dotnet-network

networks:

    angular-dotnet-network:
        driver: bridge
